stages:
  data_cleaning:
    cmd: python src\data\data_cleaning.py
    outs:
    - data/cleaned




  data_preparation:
    cmd: python data_preparation.py
    deps:
    - src\data\data_cleaning.py
    - src\data\data_preparation.py
    - data/cleaned/swiggy_cleaned.csv
    outs:
    - data/interim
